### ISSUE TITLE
Bot shows strange error of not importing dipy

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/nibotmi#23]
http://nipy.bic.berkeley.edu/builders/dipy-bdist32-35/builds/34/steps/shell_10/logs/stdio

**Comment by matthew-brett** [comment]
This appears to be a nasty interaction between Python 3.5, nose and packages installed in ``.egg`` directories.   What appears to be happening is that nose is trying to find a directory `dipy` when the actual directory is `dipy-0.11.0.dev0-py3.5-win32.egg`.  This might only happen when trying to load doctests from extension modules (not sure).  It does only happen when running through the `dipnost.py` script, and not directly through nosetests.   Stripping the file down to this, still gave the error:

```
# vim: ft=python
""" ...
"""

import sys
import nose

argv = sys.argv + ['--with-doctest']
nose.core.TestProgram(argv=argv)
```

We're running the same thing on Python 3.4 and not getting an error : http://nipy.bic.berkeley.edu/builders/dipy-bdist32-34/builds/204/steps/shell_10/logs/stdio

So, I don't know why that would be true, but for the moment, I've changed the test to use a `whl` rather than an `exe` / `easy_install` install, and it seems to be running OK: http://nipy.bic.berkeley.edu/builders/dipy-bdist32-35/builds/37/steps/shell_11/logs/stdio

**Comment by matthew-brett** [comment]
For my own reference, I used the suggestion here for debugging:  http://stackoverflow.com/questions/16200333/import-errors-when-running-nosetests-that-i-cant-reproduce-outside-of-nose

```
python dipnost.py dipy --debug=nose,nose.importer --debug-log=nose_debug
```
